/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTOCOL_PB_H_INCLUDED
#define PB_PROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Ping {
    char dummy_field;
} Ping;

typedef struct _Pong {
    char dummy_field;
} Pong;

typedef struct _Request {
    pb_size_t which_command;
    union {
        Ping ping;
    } command;
} Request;

typedef struct _Response {
    pb_size_t which_payload;
    union {
        Pong pong;
    } payload;
} Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Ping_init_default                        {0}
#define Pong_init_default                        {0}
#define Request_init_default                     {0, {Ping_init_default}}
#define Response_init_default                    {0, {Pong_init_default}}
#define Ping_init_zero                           {0}
#define Pong_init_zero                           {0}
#define Request_init_zero                        {0, {Ping_init_zero}}
#define Response_init_zero                       {0, {Pong_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Request_ping_tag                         1
#define Response_pong_tag                        1

/* Struct field encoding specification for nanopb */
#define Ping_FIELDLIST(X, a) \

#define Ping_CALLBACK NULL
#define Ping_DEFAULT NULL

#define Pong_FIELDLIST(X, a) \

#define Pong_CALLBACK NULL
#define Pong_DEFAULT NULL

#define Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,ping,command.ping),   1)
#define Request_CALLBACK NULL
#define Request_DEFAULT NULL
#define Request_command_ping_MSGTYPE Ping

#define Response_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pong,payload.pong),   1)
#define Response_CALLBACK NULL
#define Response_DEFAULT NULL
#define Response_payload_pong_MSGTYPE Pong

extern const pb_msgdesc_t Ping_msg;
extern const pb_msgdesc_t Pong_msg;
extern const pb_msgdesc_t Request_msg;
extern const pb_msgdesc_t Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Ping_fields &Ping_msg
#define Pong_fields &Pong_msg
#define Request_fields &Request_msg
#define Response_fields &Response_msg

/* Maximum encoded size of messages (where known) */
#define PROTOCOL_PB_H_MAX_SIZE                   Request_size
#define Ping_size                                0
#define Pong_size                                0
#define Request_size                             2
#define Response_size                            2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
